### PR TITLE
PR: Allow plugin to be run with Spyder 5

### LINKED ISSUE #80: Restore Spyder 5 compatibility
The idea is to make the plugin compatible with both Spyder 5 and Spyder 6 by partially reverting PR #77 .

### PR DESCRIPTION
**Pull request by jitseniesen**
## Description of Changes

Make plugin compatible with Spyder 5.4.1 and later while keeping compatibility with Spyder 6 as currently in development.

Fixes #80.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jitse Niesen

### CODE REVIEW

**Comment by ccordoba12** [comment]
Spyder 6 is going to add more breaking changes for external plugins in the coming months (not published yet, but I'm working on them).

So, I think it's better to avoid this path and simply create a stable branch here to have a version compatible with Spyder 5 and leave `master` for Spyder 6. that would make the code simpler too.

**Comment by jitseniesen** [comment]
Thanks for letting me know. I was expecting changes to the Editor and Project plugins at least.

The same question applies to the notebook and unittest; in fact it is more pertinent there because those plugins have more changes. As I see it, these are the possibilities:
* Leave the plugin master branch for Spyder 6 and don't have a stable branch for Spyder 5. This means that no release with all the improvements will be made until Spyder 6 comes out. This was the original plan but I changed track when it became clear that the release of Spyder 6 will be later than I expected.
* Move the plugin master branch back to Spyder 5 and switch to Spyder 6 only when the release is imminent. This means that we can't use the plugins to give feedback on the changes in Spyder 6 development and this approach did not work out well for Spyder 5 because it required a lot of changes and it came out at an inconvenient time for me.
* Have the plugin master branch support both Spyder 5 and Spyder 6, at least until Spyder 6 is released. That is the approach in this PR. It obviously is more work. It leads to untidy and error-prone code (for instance, the line profiler plugin class inherits from RunExecutor in Spyder 6 but not Spyder 5), and that will get worse the more Spyder 5 and Spyder 6 diverge.
* Leave the plugin master branch for Spyder 6 and have a stable branch for Spyder 5, as you suggest. That is in effect the same as the previous item, but with the Spyder 5 and Spyder 6 code in two separate git branches instead of having both Spyder 5 and Spyder 6 code in the same code base guarded by lots of "if Spyder 6:" statements. This is again more work then the first two items, it requires back porting all the changes from the master to the stable branch and making releases from both branches if the plugin is to support Spyder 6 alpha.

**Comment by ccordoba12** [comment]
> Leave the plugin master branch for Spyder 6 and have a stable branch for Spyder 5, as you suggest. That is in effect the same as the previous item, but with the Spyder 5 and Spyder 6 code in two separate git branches instead of having both Spyder 5 and Spyder 6 code in the same code base guarded by lots of "if Spyder 6:" statements.

Yep, that's the option I'd prefer, and the one we already use in Spyder and Spyder-kernels.

> This is again more work then the first two items, it requires back porting all the changes from the master to the stable branch

I think that's not necessary. You only need to forward port the fixes you do in the stable branch to the master branch. So, that shouldn't represent too much work for you (by forward porting I mean merging stable into master).

> and making releases from both branches if the plugin is to support Spyder 6 alpha.

That's up to you, of course, but I think it'd be too much work. You can keep releasing from the stable branch to fix critical bugs and changes in your dependencies, and release a new version from master after Spyder 6 is released.

**Comment by jitseniesen** [comment]
After discussion, we decided to leave the master branch of this plugin (and also the unittest and notebook plugins) compatible with Spyder 6 only. When we want to do a release targetting Spyder 5, we will create a new branch for that release and port changes when necessary after branching. This keeps the code clean and maintains a clear mapping between plugin version and Spyder version without causing too much work.

Thus, I am closing this PR without merging it.

**Pull request closed without merging**
