### PR TITLE
PR: Add natural sort for columns

### PR DESCRIPTION
**Pull request by skjerns**
It sorted columns as strings, so `10.0` was before `1.0` (see #33 )
I've inserted some code snippet from https://stackoverflow.com/questions/21030719/sort-a-pyside-qtgui-qtreewidget-by-an-alpha-numeric-column to implement natural sort on the table elements.

Additionally I've fixed a bug that prevented the 'Profile by Line' button from working (caused by `wdir` being set to `False` and the call to `self.process.setWorkingDirectory(wdir)`). Excuse that I didn't create another PR for this!

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your help with this one.

@jitseniesen, could you review this one? Thanks!

**Comment by jitseniesen** [comment]
> @jitseniesen, could you review this one? Thanks!

Sure.

**Comment by skjerns** [comment]
@jitseniesen can we merge it?

**Comment by jitseniesen** [comment]
@skjerns Sorry, I just found your PR again. Are you still interested in having it merged? If so, can you please explain the code for `natural_sort_key`, because I don't understand it?

**Comment by skjerns** [comment]
this is some code snippet that I copied from elsewhere on stackoverflow. It is especially for widgets natural sorting.

in a general sense it splits up the lines into tuples and keeps all numbers it finds as floats. Then these tuples can be compared.

e.g.
```
'34.25%'
```
will be split up into float('34.25%') and '%', so when comparing (=sorting) them, the 34.25 will be compared by it's numerical value and not by it's string value.

There are certainly easier ways to do it for this usecase, but this is a generalized solution that will also work with other items.

**Comment by jitseniesen** [comment]
Thanks, I get it now: this allows the same comparison function to be used for the text and numerical columns.

Could you please add the URL where you copied this from in a comment, and ideally add a doc string to `TreeWidgetItem` and/or `natural_sort_function` with some explanation?

> Additionally I've fixed a bug that prevented the 'Profile by Line' button from working (caused by `wdir` being set to `False` and the call to `self.process.setWorkingDirectory(wdir)`). Excuse that I didn't create another PR for this!

Can you please explain what bug this is and how I can reproduce it? The button seems to work when I tried it and I don't understand the changes you made.

**Comment by skjerns** [comment]
> Thanks, I get it now: this allows the same comparison function to be used for the text and numerical columns.
> 
> Could you please add the URL where you copied this from in a comment, and ideally add a doc string to `TreeWidgetItem` and/or `natural_sort_function` with some explanation?
>

done!


> > Additionally I've fixed a bug that prevented the 'Profile by Line' button from working (caused by `wdir` being set to `False` and the call to `self.process.setWorkingDirectory(wdir)`). Excuse that I didn't create another PR for this!
> Can you please explain what bug this is and how I can reproduce it? The button seems to work when I tried it and I don't understand the changes you made.

If you click the button once it works, but the second time it doesn't finish, this is fixed now

**Comment by skjerns** [comment]
... @jitseniesen can this be merged? one year later?

**Comment by jitseniesen** [comment]
I am sorry for taking so long. I have been rather busy recently and I rarely if ever use the plugin myself.

I am afraid I cannot reproduce the bug in the current version from git. I did try clicking the "Profile by line" button multiple times. Looking at the code, it is not obvious to me how `wdir` can be set to `False`. 

Can you explain more fully how to reproduce the bug using the current code, also mentioning what version of spyder and spyder-line-profiler you are using? Perhaps the bug is only present in the release version of spyder-line-profiler?

**Comment by skjerns** [comment]
It's some time ago, so I'm not 100% sure, but I think the problem was that the QT-function that calls the `start()` doesn't initiate `wdir` with `None`, but calls the function with `False`, making the function fail. I've added that it treats `False` the same as `None` .

I'll test this again and report back, but I'm using the release version from pip indeed.
I've already upgraded to 4.0, so line-profiler isn't working anyway anymore.

**Comment by jitseniesen** [comment]
Okay, I think I understand it now. Another user contributed commit 08b0a345838a658a6889e0b810013d38c99f6b8a in 2018 which (in a different way) fixes the problem that you are describing. However, we have never made a release with this fix in it.

I will split the natural sort commits off and merge them, because they are a nice improvement. Then we will do a release with the 2018 fix, your natural sort, and the necessary changes to make the plugin compatible with Spyder 4.

**Comment by skjerns** [comment]
great plan! thanks alot! was already wondering about the other changes in the file which weren't by me.

looking forward to using line-profiler in spyder 4.0 :)

**Comment by jitseniesen** [comment]
As mentioned above, I split the sorting part of this PR in another PR, namely #38. The other part is no longer necessary.

Thanks @skjerns for your contribution and your patience.

**Pull request closed without merging**
